engines:
  eslint:
    enabled: true
    config:
      config: '.eslintrc.json'

ratings:
  paths:
  - src/**
  - gulpfile.js

exclude_paths:
- src/images/**
- src/styles/**
- src/index.html
- src/scripts/game/generatorTable.js
- src/scripts/game/itemTable.js
- src/scripts/game/resourceTable.js