language: node_js

node_js:
- 6

cache:
  directories:
  - node_modules
sudo: false

before_script:
- npm install -g gulp-cli

script:
- gulp lint

notifications:
  email:
    on_success: never
    on_failure: never
